# Generated by Django 5.1.2 on 2024-10-24 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_produto_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='venda',
            name='status_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.statuspedido'),
        ),
    ]
