# Generated by Django 5.1.2 on 2024-10-24 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_statuspedido_alter_venda_status_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvenda',
            name='vendedor',
        ),
    ]
