# Generated by Django 5.1.2 on 2024-10-25 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_remove_itemvenda_vendedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='status_pedido',
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='status_pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loja.statuspedido'),
            preserve_default=False,
        ),
    ]
