# Generated by Django 5.1.2 on 2024-10-25 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_remove_venda_status_pedido_itemvenda_status_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvenda',
            name='cliente',
        ),
    ]
